/**
 * The A13 vocabulary as data for the bank (ROADMAP M3.2, A13, A17; DESIGN §4.1 G6, R-5.6.1).
 *
 * `web/scripts/language-terms.json` holds {@link BANNED_TERMS} and {@link NOT_BANNED} from
 * `language-lint.ts`, plus how the lint matches them. This repo owns the list; the bank's G6
 * sensitivity lint (`hb.verify.sensitivity`) reads its byte-identical copy
 * `golden/language_terms.json`, made with `uv run hb sync language-terms` there. The bank checks
 * its copy against this file, and `language-terms.test.ts` here fails while this file is stale
 * (refresh it with `npm run dump:language-terms`) or while the bank copy differs.
 *
 * The allowed texts (the R-5.6.5 sentence and the §13 disclaimer) are not exported: they belong to
 * the results page, never to an item, so the bank bans every term in item text.
 */

import { writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { BANNED_TERMS, NOT_BANNED, REPO_ROOT, type BannedTerm } from './language-lint'

/** The committed export, relative to the repo root. */
export const LANGUAGE_TERMS_PATH = 'web/scripts/language-terms.json'

/** The export's JSON shape (snake_case between repos, A17). */
export interface LanguageTermsExport {
  readonly about: string
  readonly source: string
  readonly match: { readonly flags: string; readonly wrap: string; readonly note: string }
  readonly banned_terms: readonly BannedTerm[]
  readonly not_banned: Readonly<Record<string, string>>
}

/** {@link BANNED_TERMS} and {@link NOT_BANNED} with the matching rules of `language-lint.ts`. */
export function languageTerms(): LanguageTermsExport {
  return {
    about:
      'A13 language-lint vocabulary (ROADMAP M1.20, A13; DESIGN R-5.6.1), exported for the bank G6 lint (M3.2, A17). Generated by `npm run dump:language-terms` in the public repo; do not edit.',
    source: 'web/scripts/language-lint.ts',
    match: {
      flags: 'iu',
      wrap: '(?<!\\p{L})(?:<pattern>)(?!\\p{L})',
      note: 'Each pattern is an ECMAScript regex source, matched case-insensitively between letters: anything but a letter delimits. Every example must match; no not_banned word may.',
    },
    banned_terms: BANNED_TERMS.map((t) => ({ id: t.id, pattern: t.pattern, examples: [...t.examples], why: t.why })),
    not_banned: { ...NOT_BANNED },
  }
}

/** The file text: 2-space JSON and a final newline. */
export function serializeLanguageTerms(): string {
  return `${JSON.stringify(languageTerms(), null, 2)}\n`
}

/** `npm run dump:language-terms`: rewrite the committed export. */
export function main(root: string = REPO_ROOT): number {
  const out = join(root, LANGUAGE_TERMS_PATH)
  writeFileSync(out, serializeLanguageTerms())
  console.log(`wrote ${BANNED_TERMS.length} banned terms to ${out}; copy it to the bank with \`uv run hb sync language-terms\``)
  return 0
}

// Run only as the CLI entry, so the test can import this module without writing anything.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = main()
}
