/**
 * Adaptive CAT simulation of an M1 session (ROADMAP M1.4b (b); DESIGN §7.2, §7.4, §11.2, §14.3 M1
 * acceptance 2; A2, A10, A15). SIMULATION SUPPORT ONLY: never imported by the app.
 *
 * Each simulee (true θ over the 17 axes, e.g. the M1.4a simulees of `m14a.ts`) takes one first
 * session built from the REAL engine and families:
 *
 * 1. **Plan** (A15): {@link planSession} from the engine selector (M1.14): the fixed blocks
 *    rt_simple, rt_choice4 → CAT MAT → CAT SPA → span_fwd, span_bwd, corsi → CAT QR → coding,
 *    reading, each block a generated instance of its registered family, and each CAT segment's
 *    time budget (the session target, default {@link A15_TARGET_S}, minus the blocks' E[T],
 *    shared equally).
 * 2. **Blocks** run whole: the simulated taker ({@link answerBlock}) answers from the block's own
 *    observation parameters and the family's `score()` forms the GRM / Gaussian observation (A10).
 *    The block takes the taker's own time ({@link blockTimeS}: e.g. a high-WM taker runs through
 *    more span lengths, a slow reader reads longer), not its planned E[T]; the difference moves the
 *    next CAT segment's budget, as the session clock would (M1.15).
 * 3. **CAT segments** loop (A15) on the engine's {@link selectNext} (information per second,
 *    randomesque top 5, family / sibling exclusion, coverage floor; §7.4) with the in-session
 *    per-axis EAP posterior ({@link sessionPosterior}, §11.2) and the segment's remaining time,
 *    until the selector returns nothing (axis done at SD < 0.3, or no item fits the time left).
 *    Time a segment leaves unused, or the blocks before it saved or overran, carries over to the
 *    next CAT segment, so a session ends within its target unless the blocks after the last CAT
 *    segment (coding, reading) overrun their E[T], or the blocks before it overran by more than
 *    its whole budget. Each selected item is generated by its family (`generate()`, via the
 *    selector) with its A9 params; the taker answers it ({@link answerItem}) and the family's
 *    `score()` scores it.
 * 4. **Finish** (§11.2): the correlated MAP + Laplace covariance ({@link mapTheta}) of all the
 *    session's observations against N(0, Σ_init v2), the estimate the reveal shows.
 *
 * Time: a block is charged the taker's simulated duration ({@link blockTimeS}, the family's own
 * block-time model on the simulated response); a CAT item its E[T] (`expected_time_s`, the
 * selector's own time model, §7.4: the families have no per-person item-time model), so within
 * the CAT segments the budget holds by construction and only the blocks can make a session run
 * over. Calibration (CAL) is embedded in M1.15's confidence slider, which does not exist yet, so
 * CAL, like the axes without M1 families, gets no observation and is estimated only through Σ.
 */

import { AXIS_CODES, AXIS_INDEX, N_AXES, initialSigma, type AxisCode } from '../engine/axes'
import { createRng } from '../engine/prng'
import { mapTheta, type ReadonlyMatrix } from '../engine/scorer'
import { A15_TARGET_S, COVERAGE_FLOOR, planSession, selectNext, selectionRng, sessionPosterior, type AdministeredItem } from '../engine/selector'
import type { Observation } from '../engine/types'
import type { AnyFamily } from '../tasks/family'
import { getFamily } from '../tasks/registry'
import { answerBlock, answerItem, blockTimeS } from './responders'
import { pearson, recoveryStats, type AxisRecovery } from './stats'

/** The axes the M1 CAT segments measure (A15): the M1.4b acceptance r ≥ .85 applies to them. */
export const CAT_AXES: readonly AxisCode[] = Object.freeze(['MAT', 'SPA', 'QR'] as const)
/** The axes the M1 fixed blocks measure (A10, A15). */
export const BLOCK_AXES: readonly AxisCode[] = Object.freeze(['WM', 'RT', 'PS'] as const)
/**
 * A15's M1 session is "about 25–30 min": the plan targets the midpoint ({@link A15_TARGET_S}) and
 * a session may run to the upper end, the M1.4b (b) time budget. A session runs over its target
 * only when blocks take the taker longer than their E[T] ({@link blockTimeS}).
 */
export const A15_MAX_S = 30 * 60

/** A fixed block as the session ran it. */
export interface BlockRecord {
  readonly family: string
  readonly axis: AxisCode
  readonly item_id: string
  /** The block's planned E[T] (seconds). */
  readonly expected_time_s: number
  /** Seconds the block took this taker ({@link blockTimeS}). */
  readonly time_s: number
  /** False when the block yielded no observation (its `score()` gave reasons instead). */
  readonly observed: boolean
  readonly reasons: readonly string[]
}

/** One simulated session. */
export interface SessionResult {
  readonly sessionSeed: string
  /** The MAP θ̂ at finish (canonical axis order). */
  readonly thetaHat: number[]
  /** Laplace posterior SDs at finish. */
  readonly sd: number[]
  /** CAT items administered, by axis. */
  readonly items: Partial<Record<AxisCode, number>>
  /** The administered CAT items' ids, in order (each regenerates its item, A11). */
  readonly itemIds: readonly string[]
  readonly blocks: readonly BlockRecord[]
  /** Seconds: the simulated time of every block ({@link blockTimeS}) plus the E[T] of every CAT item. */
  readonly timeS: number
  /** Seconds of CAT items. */
  readonly catTimeS: number
  /** Why each CAT segment ended: the selector's reason ('axes_done', 'time', 'exhausted', 'no_axes') or 'length' (fixed length reached). */
  readonly segmentEnds: readonly string[]
  /** Every observation the session produced (for inspection and tests). */
  readonly observations: readonly Observation[]
}

export interface SessionOptions {
  /** Session target in seconds (A15), default {@link A15_TARGET_S}. Ignored with `fixedLength`. */
  readonly targetS?: number
  /**
   * Fixed-length stopping instead of A15 time: each CAT segment loops until every one of its axes
   * has this many items (or the selector has none left), with no time limit. DESIGN §14.3 M1
   * acceptance 2 states θ recovery "at 20 items/axis"; the blocks run as usual.
   */
  readonly fixedLength?: number
  /** Prior covariance of the finish MAP and the in-session EAP (default Σ_init v2, A8). */
  readonly sigma?: ReadonlyMatrix
}

function familyOf(name: string): AnyFamily {
  const f = getFamily(name)
  if (f === undefined) throw new Error(`family ${name} is not registered`)
  return f
}

/**
 * Simulate one first session (see the module comment) for a person with true θ `theta` (17
 * axes). Deterministic in (theta, sessionSeed, options): the session's items come from
 * `sessionSeed` (as a real session's would), the taker's responses from the stream
 * `sim:<sessionSeed>` forked per step.
 */
export function simulateSession(theta: readonly number[], sessionSeed: string, opts: SessionOptions = {}): SessionResult {
  if (theta.length !== N_AXES || !theta.every(Number.isFinite)) throw new RangeError(`theta needs ${N_AXES} finite values`)
  const sigma = opts.sigma ?? initialSigma()
  const mu = new Array<number>(N_AXES).fill(0)
  const taker = createRng(`sim:${sessionSeed}`)
  const fixed = opts.fixedLength
  if (fixed !== undefined && !(Number.isInteger(fixed) && fixed >= 1)) throw new RangeError(`fixedLength must be an integer ≥ 1, got ${fixed}`)
  const plan = planSession({ sessionSeed, targetS: opts.targetS ?? A15_TARGET_S })
  const obs: Observation[] = []
  const administered: AdministeredItem[] = []
  const blocks: BlockRecord[] = []
  const items: Partial<Record<AxisCode, number>> = {}
  const segmentEnds: string[] = []
  let timeS = 0
  let catTimeS = 0
  // Seconds the next CAT segment gains over its planned budget: CAT time left unused, and each
  // block's E[T] minus its actual time (negative when a block overran), as the session clock would.
  let carry = 0
  for (const step of plan) {
    if (step.kind === 'block') {
      const { item } = step
      const { score, timeS: blockS } = answerBlock(familyOf(step.family), item, theta[AXIS_INDEX[item.axis]]!, taker.fork(`block/${step.family}`))
      if (score.observation !== undefined) obs.push(score.observation)
      blocks.push({ family: step.family, axis: item.axis, item_id: item.item_id, expected_time_s: item.expected_time_s, time_s: blockS, observed: score.observation !== undefined, reasons: score.reasons })
      timeS += blockS
      carry += item.expected_time_s - blockS
      continue
    }
    const budget = fixed === undefined ? step.budget_s + carry : Infinity
    let used = 0
    for (;;) {
      const open = fixed === undefined ? step.axes : step.axes.filter((k) => (items[k] ?? 0) < fixed)
      if (open.length === 0) {
        segmentEnds.push('length')
        break
      }
      const posterior = sessionPosterior(obs, { mu, sigma })
      const counter = administered.length
      const sel = selectNext({ sessionSeed, posterior, administered, remainingS: budget - used, sessionNumber: 1 }, selectionRng(sessionSeed, counter), { axes: open })
      if (sel.kind === 'none') {
        segmentEnds.push(sel.reason)
        break
      }
      const { item } = sel
      const answer = answerItem(familyOf(item.family), item, theta[AXIS_INDEX[item.axis]]!, taker.fork(`item/${counter}`))
      obs.push(answer.observation)
      administered.push(item)
      items[item.axis] = (items[item.axis] ?? 0) + 1
      used += item.expected_time_s
    }
    carry = fixed === undefined ? budget - used : carry
    timeS += used
    catTimeS += used
  }
  const fin = mapTheta(obs, mu, sigma)
  return {
    sessionSeed,
    thetaHat: fin.theta,
    sd: fin.cov.map((row, k) => Math.sqrt(row[k]!)),
    items,
    itemIds: administered.map((a) => a.item_id),
    blocks,
    timeS,
    catTimeS,
    segmentEnds,
    observations: obs,
  }
}

/** Min / mean / max of a sample. */
export interface Spread {
  readonly min: number
  readonly mean: number
  readonly max: number
}

function spread(xs: readonly number[]): Spread {
  let min = Infinity
  let max = -Infinity
  let sum = 0
  for (const x of xs) {
    min = Math.min(min, x)
    max = Math.max(max, x)
    sum += x
  }
  return { min, mean: sum / xs.length, max }
}

/** A CAT simulation run over many simulees. */
export interface CatRun {
  readonly n: number
  readonly seed: string
  /** The A15 session target (seconds); unused when `fixedLength` is set. */
  readonly targetS: number
  /** The fixed CAT length per axis, or null for the A15 time rule. */
  readonly fixedLength: number | null
  readonly axes: readonly AxisRecovery[]
  /** CAT items per simulee, by CAT axis. */
  readonly itemsPerAxis: Readonly<Record<string, Spread>>
  /** Session time per simulee (seconds): the blocks' simulated time plus the CAT items' E[T]. */
  readonly timeS: Spread
  readonly catTimeS: Spread
  /** Share of sessions longer than the target (blocks that took the taker longer than their E[T]). */
  readonly overTarget: number
  /**
   * Per CAT axis, Pearson r(mean b of the items a simulee was given, true θ) over the sessions with
   * items on the axis: how far the selector targets difficulty to the person (§7.4). A selector
   * blind to the responses gives ≈ 0.
   */
  readonly targeting: Readonly<Record<string, number>>
  /** Per CAT axis, the share of sessions with fewer items than the session-1 coverage floor (§7.4). */
  readonly floorShort: Readonly<Record<string, number>>
  /** Share of blocks that yielded an observation, by family. */
  readonly blockObserved: Readonly<Record<string, number>>
  /** How often each CAT segment end reason occurred. */
  readonly segmentEnds: Readonly<Record<string, number>>
  readonly sessions: readonly SessionResult[]
}

export interface CatRunOptions extends SessionOptions {
  /** Run seed; simulee i's session seed is `catsim:<seed>:<i>` (default "m14b"). */
  readonly seed?: string
  /** Called after each simulee (progress reporting). */
  readonly onSession?: (i: number, s: SessionResult) => void
}

/** The b of each CAT item a session gave on `axis`, in order (from its dichotomous observations). */
export function administeredB(s: Pick<SessionResult, 'observations'>, axis: AxisCode): number[] {
  const out: number[] = []
  for (const o of s.observations) if (o.axis === axis && (o.kind === '2pl' || o.kind === '3pl')) out.push(o.b)
  return out
}

/** r(mean administered b, true θ) on `axis` over the sessions with items on it; NaN if fewer than 2. */
export function targetingR(thetas: readonly (readonly number[])[], sessions: readonly Pick<SessionResult, 'observations'>[], axis: AxisCode): number {
  const mb: number[] = []
  const th: number[] = []
  sessions.forEach((s, i) => {
    const b = administeredB(s, axis)
    if (b.length === 0) return
    mb.push(b.reduce((x, y) => x + y, 0) / b.length)
    th.push(thetas[i]![AXIS_INDEX[axis]]!)
  })
  return mb.length < 2 ? Number.NaN : pearson(mb, th)
}

/** Simulee i's session seed in a run seeded `seed`. */
export function sessionSeedOf(seed: string, i: number): string {
  return `catsim:${seed}:${i}`
}

/**
 * Run {@link simulateSession} for each true θ in `thetas` (rows of 17) and summarise: per-axis
 * r, RMSE, mean posterior SD and 90% coverage of the finish MAP, CAT items per axis, the
 * selector's targeting and coverage-floor shortfalls, session time, block observation rates and
 * segment end reasons.
 */
export function runCat(thetas: readonly (readonly number[])[], opts: CatRunOptions = {}): CatRun {
  const n = thetas.length
  if (n < 2) throw new RangeError('runCat(): need at least 2 simulees')
  const seed = opts.seed ?? 'm14b'
  const targetS = opts.targetS ?? A15_TARGET_S
  const sessions: SessionResult[] = []
  thetas.forEach((theta, i) => {
    const s = simulateSession(theta, sessionSeedOf(seed, i), { ...opts, targetS })
    sessions.push(s)
    opts.onSession?.(i, s)
  })
  const itemsPerAxis: Record<string, Spread> = {}
  const targeting: Record<string, number> = {}
  const floorShort: Record<string, number> = {}
  for (const k of CAT_AXES) {
    itemsPerAxis[k] = spread(sessions.map((s) => s.items[k] ?? 0))
    targeting[k] = targetingR(thetas, sessions, k)
    floorShort[k] = sessions.filter((s) => (s.items[k] ?? 0) < COVERAGE_FLOOR).length / n
  }
  const blockObserved: Record<string, number> = {}
  const blockCount: Record<string, number> = {}
  for (const s of sessions) {
    for (const b of s.blocks) {
      blockCount[b.family] = (blockCount[b.family] ?? 0) + 1
      blockObserved[b.family] = (blockObserved[b.family] ?? 0) + (b.observed ? 1 : 0)
    }
  }
  for (const f of Object.keys(blockCount)) blockObserved[f] = blockObserved[f]! / blockCount[f]!
  const segmentEnds: Record<string, number> = {}
  for (const s of sessions) for (const e of s.segmentEnds) segmentEnds[e] = (segmentEnds[e] ?? 0) + 1
  return {
    n,
    seed,
    targetS,
    fixedLength: opts.fixedLength ?? null,
    axes: recoveryStats(
      thetas,
      sessions.map((s) => s.thetaHat),
      sessions.map((s) => s.sd),
    ),
    itemsPerAxis,
    timeS: spread(sessions.map((s) => s.timeS)),
    catTimeS: spread(sessions.map((s) => s.catTimeS)),
    overTarget: sessions.filter((s) => s.timeS > targetS + 1e-9).length / n,
    targeting,
    floorShort,
    blockObserved,
    segmentEnds,
    sessions,
  }
}

/**
 * The axes of a run with observations (in any session): the coverage acceptance applies to them.
 * An axis with none (e.g. LR in M1) is estimated only through Σ. QR counts although a session
 * whose span blocks overran can end with no QR item (see `floorShort`).
 */
export function observedAxes(run: CatRun): AxisCode[] {
  return AXIS_CODES.filter((k) => run.sessions.some((s) => s.observations.some((o) => o.axis === k)))
}
