/**
 * Postgres without the host's System V shared memory (ROADMAP M2.0, A6).
 *
 * The problem. A Postgres server needs one System V shared-memory segment even when its real shared
 * memory is an anonymous mmap: a 56-byte header that locks the data directory. macOS leaks the
 * kernel's accounting of those segments when a postmaster is killed (`ipcs` shows nothing, but
 * `kern.sysv.shmall` stays used up), after which every `shmget()` fails with ENOMEM and so does
 * `initdb`, until the machine reboots. The workflow watchdog kills runs with SIGKILL, so on an
 * autonomous Mac that is a matter of time; and `shmmni` is only 32 segments for all the runs at once.
 * Setting `shared_memory_type=mmap` does not help (checked: `shmget(key, size=56)` still fails), and
 * raising the limits needs root and a reboot. PGlite has no `statement_timeout` and one session, so
 * it cannot run the suite (supabase/README.md, ADR M2.0).
 *
 * The fix, macOS only. The server gets its four shared-memory calls from a tiny library
 * (shm/hb_shm_shim.c) that backs them with anonymous shared mappings, which the kernel releases when
 * the process dies. It is loaded with `DYLD_INSERT_LIBRARIES`, and macOS honours that only for
 * binaries without the hardened runtime, so a COPY of `postgres` is re-signed ad hoc (the npm
 * package's own files are never changed). `initdb` starts `postgres` through `/bin/sh`, which strips
 * `DYLD_*` from the environment, so the copy sits behind a two-line wrapper script that sets the
 * variable itself with `env`. The result is an overlay of the package's `native/` directory:
 *
 *   <cache>/<key>/libhbshm.dylib     the shim, built with the system `cc` (Xcode command line tools)
 *   <cache>/<key>/bin/initdb         a copy (its signature stays valid; it needs no shim itself)
 *   <cache>/<key>/bin/postgres       the wrapper: initdb finds `postgres` next to itself
 *   <cache>/<key>/bin/postgres.real  the re-signed copy
 *   <cache>/<key>/lib, share         symlinks into the package
 *
 * `<key>` hashes the shim source, the architecture and the binaries (size, mtime, package version),
 * so an upgrade or an edit builds a new overlay. Builds go to a temp directory and are renamed into
 * place, so concurrent runs (several agents, several test processes) never see half an overlay.
 *
 * Linux has none of this problem (large kernel limits, nothing leaks), so nothing is built there.
 */

import { execFileSync } from 'node:child_process'
import { createHash, randomBytes } from 'node:crypto'
import { chmodSync, copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, symlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { isAlive } from './proc'

/** The C source of the shared-memory shim. */
export const SHIM_SOURCE = fileURLToPath(new URL('./shm/hb_shm_shim.c', import.meta.url))

/** Bump when the build recipe below changes, so old overlays are not reused. */
const RECIPE = 'v1'
const READY = 'READY'
const DYLIB = 'libhbshm.dylib'
const BUILD_PREFIX = '.build-'

/** The package's own `native/` directory: what the overlay is made from. */
export interface RealBinaries {
  readonly root: string
  readonly initdb: string
  readonly postgres: string
}

export interface ShimmedBinaries {
  /** The overlay directory (`<cache>/<key>`). */
  readonly dir: string
  readonly initdb: string
  /** The wrapper script: run this, not `postgres.real`. */
  readonly postgres: string
  readonly dylib: string
  /** False when an overlay that was already there is reused. */
  readonly built: boolean
}

export interface ShimOptions {
  /** Where overlays are cached, in order of preference; the first one that can be created is used. */
  readonly cacheDirs: readonly string[]
  /** `process.arch` by default. */
  readonly arch?: string
}

/**
 * What `postgres` becomes inside the overlay. It sets the variable itself, with `env`, because the
 * `/bin/sh` that `initdb` starts it through removes `DYLD_*` from its own environment (System
 * Integrity Protection) but does pass what is on a command line; `exec` keeps the pid, so the
 * postmaster's pid file and signals are the real server's.
 */
export const WRAPPER_SCRIPT = `#!/bin/sh
# Generated by web/scripts/db/shm.ts: runs the re-signed postgres with the System V shared-memory shim.
here=$(cd "$(dirname "$0")" && pwd -P) || exit 127
exec /usr/bin/env "DYLD_INSERT_LIBRARIES=\${here%/bin}/${DYLIB}" "$here/postgres.real" "$@"
`

function clangArch(arch: string): string {
  if (arch === 'arm64') return 'arm64'
  if (arch === 'x64') return 'x86_64'
  throw new Error(`The shared-memory shim is built for macOS arm64 and x64, not ${arch}.`)
}

/** The cache key for these binaries (16 hex characters). */
export function shimKey(real: RealBinaries, arch: string = process.arch): string {
  const h = createHash('sha256')
  h.update(RECIPE).update('\0').update(arch).update('\0').update(readFileSync(SHIM_SOURCE))
  for (const file of [real.postgres, real.initdb]) {
    const s = statSync(file)
    h.update('\0').update(`${file}:${s.size}:${Math.round(s.mtimeMs)}`)
  }
  try {
    h.update('\0').update(readFileSync(join(real.root, '..', 'package.json')))
  } catch {
    // The package.json only adds to the key.
  }
  return h.digest('hex').slice(0, 16)
}

function overlayAt(dir: string, built: boolean): ShimmedBinaries {
  return { dir, initdb: join(dir, 'bin', 'initdb'), postgres: join(dir, 'bin', 'postgres'), dylib: join(dir, DYLIB), built }
}

function isBuilt(dir: string): boolean {
  return [READY, DYLIB, join('bin', 'initdb'), join('bin', 'postgres'), join('bin', 'postgres.real')].every((f) => existsSync(join(dir, f)))
}

function run(file: string, args: readonly string[], what: string): string {
  try {
    return execFileSync(file, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 120_000 })
  } catch (e) {
    const err = e as Error & { stderr?: string; code?: string }
    const detail = (err.stderr ?? '').trim() || err.message
    if (err.code === 'ENOENT') throw new Error(`${what}: \`${file}\` was not found. On macOS install the command line tools: xcode-select --install`, { cause: e })
    throw new Error(`${what} failed: ${detail}`, { cause: e })
  }
}

/** Removes `.build-<pid>-…` directories whose builder died. */
function sweepStaleBuilds(cacheDir: string): void {
  for (const name of readdirSync(cacheDir)) {
    if (!name.startsWith(BUILD_PREFIX)) continue
    const pid = Number.parseInt(name.slice(BUILD_PREFIX.length), 10)
    if (Number.isInteger(pid) && !isAlive(pid)) rmSync(join(cacheDir, name), { recursive: true, force: true })
  }
}

function assemble(dir: string, real: RealBinaries, arch: string): void {
  mkdirSync(join(dir, 'bin'))
  const cc = process.env.CC ?? 'cc'
  run(cc, ['-O2', '-Wall', '-Wextra', '-dynamiclib', '-arch', clangArch(arch), '-o', join(dir, DYLIB), SHIM_SOURCE], 'Building the shared-memory shim')

  copyFileSync(real.initdb, join(dir, 'bin', 'initdb'))
  copyFileSync(real.postgres, join(dir, 'bin', 'postgres.real'))
  for (const exe of ['initdb', 'postgres.real']) chmodSync(join(dir, 'bin', exe), 0o755)
  // Ad hoc, without the hardened runtime the npm package's signature carries: only then does macOS
  // honour DYLD_INSERT_LIBRARIES for this binary.
  run('/usr/bin/codesign', ['--force', '--sign', '-', join(dir, 'bin', 'postgres.real')], 'Re-signing the postgres copy')

  symlinkSync(join(real.root, 'lib'), join(dir, 'lib'))
  symlinkSync(join(real.root, 'share'), join(dir, 'share'))
  writeFileSync(join(dir, 'bin', 'postgres'), WRAPPER_SCRIPT, { mode: 0o755 })

  const version = run(join(dir, 'bin', 'postgres'), ['-V'], 'Running the shimmed postgres')
  if (!version.includes('PostgreSQL')) throw new Error(`Running the shimmed postgres printed ${JSON.stringify(version)}`)
  writeFileSync(join(dir, READY), `${new Date().toISOString()}\n`)
}

/**
 * Builds the overlay for these binaries, or returns the one already built. Safe to call from
 * several processes at once. Throws, with the compiler's or codesign's message, if it cannot.
 */
export function buildShimmedBinaries(real: RealBinaries, options: ShimOptions): ShimmedBinaries {
  const arch = options.arch ?? process.arch
  const key = shimKey(real, arch)
  let cannotCreate: unknown
  for (const cacheDir of options.cacheDirs) {
    // DYLD_INSERT_LIBRARIES is a colon-separated list.
    if (cacheDir.includes(':')) {
      cannotCreate = new Error(`cache directory ${cacheDir} contains a colon`)
      continue
    }
    const final = join(cacheDir, key)
    if (isBuilt(final)) return overlayAt(final, false)
    let tmp: string
    try {
      mkdirSync(cacheDir, { recursive: true })
      sweepStaleBuilds(cacheDir)
      tmp = join(cacheDir, `${BUILD_PREFIX}${process.pid}-${randomBytes(4).toString('hex')}`)
      mkdirSync(tmp)
    } catch (e) {
      cannotCreate = e
      continue
    }
    try {
      assemble(tmp, real, arch)
      // A directory under this key without the marker is a damaged overlay; it is only ours to replace.
      if (existsSync(final) && !isBuilt(final)) rmSync(final, { recursive: true, force: true })
      try {
        renameSync(tmp, final)
      } catch (e) {
        // Another process renamed its identical build first.
        if (!isBuilt(final)) throw e
        rmSync(tmp, { recursive: true, force: true })
        return overlayAt(final, false)
      }
      return overlayAt(final, true)
    } catch (e) {
      rmSync(tmp, { recursive: true, force: true })
      throw e
    }
  }
  throw new Error(`No writable directory for the shared-memory shim (tried ${options.cacheDirs.join(', ')}).`, { cause: cannotCreate })
}
